Fix CI Java build using correct Autotools env var (closes #1883)
OpenLightingProject/ola pull request #1885
Opened 2023-07-26 20:34 UTC by DaAwesomeP

This supersedes #1883 and solves the issue found in #1881.

2023-07-26 23:56 UTC, peternewman requested changes
Do you want to try and fix the codespell typos too?

2023-07-26 23:56 UTC, peternewman commented on .github/workflows/build.yaml
> +          echo "DISTCHECK_CONFIGURE_FLAGS=${{ matrix.configure-args }} CPPFLAGS=-Wno-deprecated-declarations" >> $GITHUB_ENV
I think this is redundant from my shonky testing isn't it?
```suggestion
```

2023-07-27 13:13 UTC, peternewman commented
The distcheck is failing, it looks because this isn't in 0.10, so it might be easiest to just skip testing the Java stuff on 0.10, but the new distcheck stuff can then go into master too, where Java should build, or might need the Java updates from #1882 :
https://github.com/OpenLightingProject/ola/pull/702/files

2023-07-27 14:17 UTC, DaAwesomeP commented
> Do you want to try and fix the codespell typos too?

See #1886.

> The distcheck is failing, it looks because this isn't in 0.10, so it might be easiest to just skip testing the Java stuff on 0.10, but the new distcheck stuff can then go into master too, where Java should build, or might need the Java updates from #1882 : https://github.com/OpenLightingProject/ola/pull/702/files

OK, I modified this to fix the distcheck stuff but disable Java for now. Your following pull can re-enable it.

2023-08-02 18:32 UTC, DaAwesomeP commented
@peternewman polite ping!

2023-08-09 10:34 UTC, peternewman approved these changes
LGTM thanks!

2023-08-09 10:34 UTC, merged